export const db_KindCatch = {
  instructionDuration: 10,
  instruction:
    'Saluhin ang mga nahuhulog na mabuting gawain at iwasan ang mga masasamang gagawin.',
  narrator: 'uni',
  grade: [
    {
      kindnessList: [
        { id: 1, kindness: 'Pagmamano' },
        { id: 2, kindness: 'Pagsunod sa utos' },
        { id: 3, kindness: 'Pagtulong' },
        { id: 4, kindness: 'Pagrespeto' },
        { id: 5, kindness: 'Pagpapasalamat' },
        { id: 6, kindness: 'Pagdarasal' },
        { id: 7, kindness: 'Maging tapat' },
        { id: 8, kindness: 'Pagdarasal' },
        { id: 9, kindness: 'Pagrespeto' },
        { id: 10, kindness: 'Pagpapasalamat' },
        { id: 11, kindness: 'Pagrespeto' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Pagtulong' },
        { id: 14, kindness: 'Pagmamano' },
        { id: 15, kindness: 'Pagsunod sa utos' },
      ],
      badList: [
        { id: 1, badness: 'Pamimintas' },
        { id: 2, badness: 'Paninigaw' },
        { id: 3, badness: 'Pakikipag-away' },
        { id: 4, badness: 'Pambubulas' },
        { id: 5, badness: 'Pagnanakaw' },
        { id: 6, badness: 'Pagkakalat ng basura' },
        { id: 7, badness: 'Paninigaw' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Pamimintas' },
        { id: 10, badness: 'Paninigaw' },
      ],
    },
    {
      kindnessList: [
        { id: 1, kindness: 'Magalang' },
        { id: 2, kindness: 'Madasalin' },
        { id: 3, kindness: 'Matulungin' },
        { id: 4, kindness: 'Makabayan' },
        { id: 5, kindness: 'Masipag' },
        { id: 6, kindness: 'Magalang' },
        { id: 7, kindness: 'Madasalin' },
        { id: 8, kindness: 'Matulungin' },
        { id: 9, kindness: 'Makabayan' },
        { id: 10, kindness: 'Masipag' },
        { id: 11, kindness: 'Magalang' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Matulungin' },
        { id: 14, kindness: 'Makabayan' },
        { id: 15, kindness: 'Masipag' },
      ],
      badList: [
        { id: 1, badness: 'Pakyu!' },
        { id: 2, badness: 'Gagu ka!' },
        { id: 3, badness: 'Tanginamu gagu' },
        { id: 4, badness: 'Fucking Hell' },
        { id: 5, badness: 'Piece of shit!' },
        { id: 6, badness: 'Pakyu!' },
        { id: 7, badness: 'Gagu ka!' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Fucking Hell' },
        { id: 10, badness: 'Piece of shit!' },
      ],
    },
    {
      kindnessList: [
        { id: 1, kindness: 'Magalang' },
        { id: 2, kindness: 'Madasalin' },
        { id: 3, kindness: 'Matulungin' },
        { id: 4, kindness: 'Makabayan' },
        { id: 5, kindness: 'Masipag' },
        { id: 6, kindness: 'Magalang' },
        { id: 7, kindness: 'Madasalin' },
        { id: 8, kindness: 'Matulungin' },
        { id: 9, kindness: 'Makabayan' },
        { id: 10, kindness: 'Masipag' },
        { id: 11, kindness: 'Magalang' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Matulungin' },
        { id: 14, kindness: 'Makabayan' },
        { id: 15, kindness: 'Masipag' },
      ],
      badList: [
        { id: 1, badness: 'Pakyu!' },
        { id: 2, badness: 'Gagu ka!' },
        { id: 3, badness: 'Tanginamu gagu' },
        { id: 4, badness: 'Fucking Hell' },
        { id: 5, badness: 'Piece of shit!' },
        { id: 6, badness: 'Pakyu!' },
        { id: 7, badness: 'Gagu ka!' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Fucking Hell' },
        { id: 10, badness: 'Piece of shit!' },
      ],
    },
  ],
}
