export const db_KindCatch = {
  grade: [
    {
      kindnessList: [
        { id: 1, kindness: 'Magalang' },
        { id: 2, kindness: 'Madasalin' },
        { id: 3, kindness: 'Matulungin' },
        { id: 4, kindness: 'Makabayan' },
        { id: 5, kindness: 'Masipag' },
        { id: 6, kindness: 'Magalang' },
        { id: 7, kindness: 'Madasalin' },
        { id: 8, kindness: 'Matulungin' },
        { id: 9, kindness: 'Makabayan' },
        { id: 10, kindness: 'Masipag' },
        { id: 11, kindness: 'Magalang' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Matulungin' },
        { id: 14, kindness: 'Makabayan' },
        { id: 15, kindness: 'Masipag' },
      ],
      badList: [
        { id: 1, badness: 'Pakyu!' },
        { id: 2, badness: 'Gagu ka!' },
        { id: 3, badness: 'Tanginamu gagu' },
        { id: 4, badness: 'Fucking Hell' },
        { id: 5, badness: 'Piece of shit!' },
        { id: 6, badness: 'Pakyu!' },
        { id: 7, badness: 'Gagu ka!' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Fucking Hell' },
        { id: 10, badness: 'Piece of shit!' },
      ],
    },
    {
      kindnessList: [
        { id: 1, kindness: 'Magalang' },
        { id: 2, kindness: 'Madasalin' },
        { id: 3, kindness: 'Matulungin' },
        { id: 4, kindness: 'Makabayan' },
        { id: 5, kindness: 'Masipag' },
        { id: 6, kindness: 'Magalang' },
        { id: 7, kindness: 'Madasalin' },
        { id: 8, kindness: 'Matulungin' },
        { id: 9, kindness: 'Makabayan' },
        { id: 10, kindness: 'Masipag' },
        { id: 11, kindness: 'Magalang' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Matulungin' },
        { id: 14, kindness: 'Makabayan' },
        { id: 15, kindness: 'Masipag' },
      ],
      badList: [
        { id: 1, badness: 'Pakyu!' },
        { id: 2, badness: 'Gagu ka!' },
        { id: 3, badness: 'Tanginamu gagu' },
        { id: 4, badness: 'Fucking Hell' },
        { id: 5, badness: 'Piece of shit!' },
        { id: 6, badness: 'Pakyu!' },
        { id: 7, badness: 'Gagu ka!' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Fucking Hell' },
        { id: 10, badness: 'Piece of shit!' },
      ],
    },
    {
      kindnessList: [
        { id: 1, kindness: 'Magalang' },
        { id: 2, kindness: 'Madasalin' },
        { id: 3, kindness: 'Matulungin' },
        { id: 4, kindness: 'Makabayan' },
        { id: 5, kindness: 'Masipag' },
        { id: 6, kindness: 'Magalang' },
        { id: 7, kindness: 'Madasalin' },
        { id: 8, kindness: 'Matulungin' },
        { id: 9, kindness: 'Makabayan' },
        { id: 10, kindness: 'Masipag' },
        { id: 11, kindness: 'Magalang' },
        { id: 12, kindness: 'Madasalin' },
        { id: 13, kindness: 'Matulungin' },
        { id: 14, kindness: 'Makabayan' },
        { id: 15, kindness: 'Masipag' },
      ],
      badList: [
        { id: 1, badness: 'Pakyu!' },
        { id: 2, badness: 'Gagu ka!' },
        { id: 3, badness: 'Tanginamu gagu' },
        { id: 4, badness: 'Fucking Hell' },
        { id: 5, badness: 'Piece of shit!' },
        { id: 6, badness: 'Pakyu!' },
        { id: 7, badness: 'Gagu ka!' },
        { id: 8, badness: 'Tanginamu gagu' },
        { id: 9, badness: 'Fucking Hell' },
        { id: 10, badness: 'Piece of shit!' },
      ],
    },
  ],
}
