export const db_KindCatch = {
  grade: [
    [
      {
        id: 'ac-20231122-e0a53cde-be49-43ca-8b49-c45338a27602',
        instructionDuration: 10,
        instruction:
          'Saluhin ang mga nahuhulog na mabuting prinsipyo at iwasan ang mga masasamang prinsipyo.',
        narrator: 'uni',
        kindnessList: [
          { id: 1, kindness: 'Pagmamano' },
          { id: 2, kindness: 'Pagsunod sa utos' },
          { id: 3, kindness: 'Pagtulong' },
          { id: 4, kindness: 'Pagrespeto' },
          { id: 5, kindness: 'Pagpapasalamat' },
          { id: 6, kindness: 'Pagdarasal' },
          { id: 7, kindness: 'Maging tapat' },
          { id: 8, kindness: 'Pagdarasal' },
          { id: 9, kindness: 'Pagrespeto' },
          { id: 10, kindness: 'Pagpapasalamat' },
          { id: 11, kindness: 'Pagrespeto' },
          { id: 12, kindness: 'Madasalin' },
          { id: 13, kindness: 'Pagtulong' },
          { id: 14, kindness: 'Pagmamano' },
          { id: 15, kindness: 'Pagsunod sa utos' },
        ],
        badList: [
          { id: 1, badness: 'Pamimintas' },
          { id: 2, badness: 'Paninigaw' },
          { id: 3, badness: 'Pakikipag-away' },
          { id: 4, badness: 'Pambubulas' },
          { id: 5, badness: 'Pagnanakaw' },
          { id: 6, badness: 'Pagkalat ng basura' },
          { id: 7, badness: 'Paninigaw' },
          { id: 8, badness: 'Pakikipag-away' },
          { id: 9, badness: 'Pamimintas' },
          { id: 10, badness: 'Paninigaw' },
        ],
      },
    ],
    [
      {
        id: 'ac-20231122-6dc4077d-1328-473e-a944-796302f56890',
        instructionDuration: 10,
        instruction:
          'Saluhin ang mga nahuhulog na mabuting gawain at iwasan ang mga masasamang gagawin.',
        narrator: 'uni',
        kindnessList: [
          { id: 1, kindness: 'Magtiwala' },
          { id: 2, kindness: 'Pagmamahal' },
          { id: 3, kindness: 'Makisalamuha' },
          { id: 4, kindness: 'Pagtulong' },
          { id: 5, kindness: 'Magiliwin' },
          { id: 6, kindness: 'Masinop' },
          { id: 7, kindness: 'Maging Malinis' },
          { id: 8, kindness: 'Matulungin' },
          { id: 9, kindness: 'Makabayan' },
          { id: 10, kindness: 'Pag-unawa' },
          { id: 11, kindness: 'Masinop' },
          { id: 12, kindness: 'Magiliwin' },
          { id: 13, kindness: 'Pagmamahal' },
          { id: 14, kindness: 'Makabayan' },
          { id: 15, kindness: 'Pagtulong' },
        ],
        badList: [
          { id: 1, badness: 'Mangutya' },
          { id: 2, badness: 'Pangmamaliit' },
          { id: 3, badness: 'Magyabang' },
          { id: 4, badness: 'Pang-aapi' },
          { id: 5, badness: 'Pang-mamaliit' },
          { id: 6, badness: 'Wag mamansin' },
          { id: 7, badness: 'Makasarili' },
          { id: 8, badness: 'Panghihiya' },
          { id: 9, badness: 'Magmaktol' },
          { id: 10, badness: 'Wag mamansin' },
        ],
      },
    ],
    [
      {
        id: 1,
        instructionDuration: 10,
        instruction:
          'Saluhin ang mga nahuhulog na mabuting gawain at iwasan ang mga masasamang gagawin.',
        narrator: 'uni',
        kindnessList: [
          { id: 1, kindness: 'Magalang' },
          { id: 2, kindness: 'Madasalin' },
          { id: 3, kindness: 'Matulungin' },
          { id: 4, kindness: 'Makabayan' },
          { id: 5, kindness: 'Masipag' },
          { id: 6, kindness: 'Magalang' },
          { id: 7, kindness: 'Madasalin' },
          { id: 8, kindness: 'Matulungin' },
          { id: 9, kindness: 'Makabayan' },
          { id: 10, kindness: 'Masipag' },
          { id: 11, kindness: 'Magalang' },
          { id: 12, kindness: 'Madasalin' },
          { id: 13, kindness: 'Matulungin' },
          { id: 14, kindness: 'Makabayan' },
          { id: 15, kindness: 'Masipag' },
        ],
        badList: [
          { id: 1, badness: 'Pamimintas' },
          { id: 2, badness: 'Paninigaw' },
          { id: 3, badness: 'Pakikipag-away' },
          { id: 4, badness: 'Pambubulas' },
          { id: 5, badness: 'Pagnanakaw' },
          { id: 6, badness: 'Pagkakalat ng basura' },
          { id: 7, badness: 'Paninigaw' },
          { id: 8, badness: 'Pakikipag-away' },
          { id: 9, badness: 'Pamimintas' },
          { id: 10, badness: 'Paninigaw' },
        ],
      },
    ],
  ],
}
