export const ACTIVITIES_GOODHABITS = [
  {
    id: 1,
    actNum: 1,
    title: 'Title',
    date: '2023-1-11',
    score: 12,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 2,
    actNum: 2,
    title: 'Title',
    date: '2023-1-15',
    score: 10,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 3,
    actNum: 3,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 4,
    actNum: 4,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
]

export const ACTIVITIES_TRADITIONS = [
  {
    id: 1,
    actNum: 1,
    title: 'Title',
    date: '2023-1-11',
    score: 10,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 2,
    actNum: 1,
    title: 'Title',
    date: '2023-1-15',
    score: 8,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 3,
    actNum: 3,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 4,
    actNum: 4,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
]

export const ACTIVITIES_VALUES = [
  {
    id: 1,
    actNum: 1,
    title: 'Title',
    date: '2023-1-11',
    score: 9,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 2,
    actNum: 2,
    title: 'Title',
    date: '2023-1-15',
    score: 10,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 3,
    actNum: 3,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
  {
    id: 4,
    actNum: 4,
    title: 'Title',
    date: '',
    score: 0,
    items: 12,
    img: require('../img/empty-bg.png'),
  },
]
