export const corresIcon = {
  1: { id: 1, link: require('../img/avatars/avatar-1.png') },
  2: { id: 2, link: require('../img/avatars/avatar-2.png') },
  3: { id: 3, link: require('../img/avatars/avatar-3.png') },
  4: { id: 4, link: require('../img/avatars/avatar-4.png') },
  5: { id: 5, link: require('../img/avatars/avatar-5.png') },
  6: { id: 6, link: require('../img/avatars/avatar-6.png') },
  7: { id: 7, link: require('../img/avatars/avatar-7.png') },
  8: { id: 8, link: require('../img/avatars/avatar-8.png') },
  9: { id: 7, link: require('../img/avatars/avatar-9.png') },
  10: { id: 8, link: require('../img/avatars/avatar-10.png') },
  11: { id: 7, link: require('../img/avatars/avatar-11.png') },
  12: { id: 8, link: require('../img/avatars/avatar-12.png') },
  13: { id: 7, link: require('../img/avatars/avatar-13.png') },
  14: { id: 8, link: require('../img/avatars/avatar-14.png') },
  15: { id: 7, link: require('../img/avatars/avatar-15.png') },
  16: { id: 8, link: require('../img/avatars/avatar-16.png') },
}
