export const getImg = {
  bg: {
    bahayKubo: { link: require('../img/bg/bahay-kubo.png') },
    table: { link: require('../img/bg/table.jpeg') },
    emptyBg: { link: require('../img/bg/empty-bg.png') },
    jeepInterior: { link: require('../img/bg/jeepInterior.png') },
    lwGreenTop: { link: require('../img/bg/layered-waves-green-1.png') },
    tableZoomedIn: { link: require('../img/bg/lessons.png') },
    records: { link: require('../img/bg/records.png') },
  },
  components: {
    records: { link: require('../img/buttons/records.png') },
    books: { link: require('../img/buttons/books.png') },
    jeepRed: { link: require('../img/buttons/jeep-red.png') },
    basket: { link: require('../img/act/kindness-catcher/basket.png') },
    apple: { link: require('../img/act/kindness-catcher/apple.png') },
    badApple: { link: require('../img/act/kindness-catcher/bad-apple.png') },
    mabait: { link: require('../img/act/arr-the-val/options/mabait.png') },
    masama: { link: require('../img/act/arr-the-val/options/masama.png') },
    bookValues: { link: require('../img/buttons/book-values.png') },
    bookTraditions: { link: require('../img/buttons/book-traditions.png') },
    bookGoodHabits: { link: require('../img/buttons/book-good-habits.png') },
    cardValues: { link: require('../img/buttons/card-values.png') },
    cardTraditions: { link: require('../img/buttons/card-traditions.png') },
    cardGoodHabits: { link: require('../img/buttons/card-good-habits.png') },
    shadow: { link: require('../img/buttons/shadow.png') },
  },
}
